version: 2
jobs:
  build:
    working_directory: ~/blockstack-app
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          # https://circleci.com/docs/2.0/caching/
          key: yarn-packages-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "package.json" }}
          paths:
            - ./.cache/yarn
      # - run: # run coverage report
      #     name: code-coverage
      #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - run:
          name: Test suite
          command: yarn test --passWithNoTests
      - run: 
          name: Lint Prettier
          command: yarn lint:prettier
      - run:
          name: Lint ESLint
          command: yarn lint:eslint
      - run:
          name: typecheck
          command: yarn typecheck
      - run:
          name: Build extension
          command: yarn prod:ext && zip -r extension.zip dist
      - store_artifacts:
          path: extension.zip
